namespace Hidistro.Entities.Store
{
    using System;

    public enum Privilege
    {
        AddMemberGrade = 0x138d,
        AddProductCategory = 0xbce,
        AddProducts = 0xbba,
        AddProductType = 0xbca,
        BrandCategories = 0xbd1,
        ClientActivy = 0x1b61,
        ClientGroup = 0x1b5f,
        ClientNew = 0x1b60,
        ClientSleep = 0x1b62,
        CofimOrderPay = 0xfa4,
        CountDown = 0x1f46,
        Coupons = 0x1f47,
        DeleteMember = 0x138b,
        DeleteMemberGrade = 0x138f,
        DeleteOrder = 0xfa2,
        DeleteProductCategory = 0xbd0,
        DeleteProducts = 0xbbc,
        DeleteProductType = 0xbcc,
        EditMember = 0x138a,
        EditMemberGrade = 0x138e,
        EditOrders = 0xfa3,
        EditProductCategory = 0xbcf,
        EditProducts = 0xbbb,
        EditProductType = 0xbcb,
        ExpressComputerpes = 0x3ef,
        ExpressPrint = 0xfa6,
        ExpressTemplates = 0xfa9,
        Gifts = 0x1f41,
        GroupBuy = 0x1f45,
        InStockProduct = 0xbbd,
        MemberArealDistributionStatistics = 0x2718,
        MemberGrades = 0x138c,
        MemberRanking = 0x2717,
        Members = 0x1389,
        OffShelfProducts = 0xbbf,
        OrderPromotion = 0x1f43,
        OrderRefundApply = 0xfac,
        OrderReplaceApply = 0xfad,
        OrderReturnsApply = 0xfae,
        Orders = 0xfa1,
        OrderSendGoods = 0xfa5,
        OrderStatistics = 0x2712,
        PaymentModes = 0x3ec,
        PictureMange = 0x3f1,
        ProductBatchExport = 0xbd2,
        ProductBatchUpload = 0xbc4,
        ProductCategory = 0xbcd,
        ProductPromotion = 0x1f42,
        Products = 0xbb9,
        ProductSaleRanking = 0x2715,
        ProductSaleStatistics = 0x2716,
        ProductTypes = 0xbc9,
        ProductUnclassified = 0xbc2,
        RemarkOrder = 0xfa8,
        SaleDetails = 0x2713,
        SaleReport = 0x2711,
        SaleTargets = 0x2714,
        Shippers = 0xfaa,
        ShippingModes = 0x3ed,
        ShippingTemplets = 0x3ee,
        SiteSettings = 0x3e9,
        SubjectProducts = 0xbc3,
        Summary = 0x3e8,
        UpShelfProducts = 0xbbe,
        UserIncreaseStatistics = 0x2719,
        Votes = 0x7d9
    }
}

