namespace Hidistro.Entities.Orders
{
    using System;

    public enum OrderActions
    {
        BUYER_CONFIRM_GOODS = 2,
        BUYER_PAY = 1,
        MASTER_SELLER_MODIFY_DELIVER_ADDRESS = 11,
        MASTER_SELLER_MODIFY_GIFTS = 14,
        MASTER_SELLER_MODIFY_PAYMENT_MODE = 12,
        MASTER_SELLER_MODIFY_SHIPPING_MODE = 13,
        SELLER_CLOSE = 10,
        SELLER_CONFIRM_PAY = 7,
        SELLER_FINISH_TRADE = 0x10,
        SELLER_MODIFY_TRADE = 8,
        SELLER_REJECT_REFUND = 9,
        SELLER_SEND_GOODS = 6,
        SUBSITE_CREATE_PURCHASEORDER = 0x11,
        SUBSITE_SELLER_MODIFY_DELIVER_ADDRESS = 3,
        SUBSITE_SELLER_MODIFY_GIFTS = 15,
        SUBSITE_SELLER_MODIFY_PAYMENT_MODE = 4,
        SUBSITE_SELLER_MODIFY_SHIPPING_MODE = 5
    }
}

